name: hs-server-starter
version: 0.1.0.0
synopsis: Write a server supporting Server::Starter's protocol in Haskell
description: ! 'Provides a utility to write server program which can be

  called via Perl''s https://github.com/kazuho/p5-Server-Starter

  program using Haskell.

  This module does not provide a Haskell implementation of

  start_server, so you need to use the original Perl version

  or use a version ported to golang.'
category: value
author: Masahiro Honma
maintainer: hiratara@cpan.org
copyright: Copyright 2017- hiratara
license: BSD3
github: hiratara/hs-server-starter
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Network.ServerStarter.Socket
  dependencies:
  - base >=4.7 && <5
  - directory >=1.3.0.0 && <1.4
  - network >=2.6.3.1 && <2.7
executables:
  server-starter-warp-example:
    main: server-starter-warp-example.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hs-server-starter
    - http-types
    - warp
    - wai
    - network
    when:
    - condition: ! '!(flag(example))'
      buildable: false
tests:
  hs-server-starter-test:
    main: test-ss-socket.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hs-server-starter
    - network
    - temporary
    - unix
    - HUnit
flags:
  example:
    description: Build the example application
    manual: false
    default: false
